### ISSUE TITLE
two problem for framework

### ISSUE THREAD

**Issue by diybl** [KumoKyaku/Megumin.Net#12]
1、建议将MessageThreadTransducer删掉，将里面的 列队 移入 remote 类里
      一个remote跑一个线程，一个程序可以创建多个remote，有点像actor的雏形
      MessageThreadTransducer的实现 变成remote的update 
2、以下为1改动后的描述
      remote 加一个eventobject 比如 ManualResetEvent event = new ManualResetEvent(false);
      当每push一个列队的时候 event.Set( );
     
      游戏的逻辑线程 ：
      private void MyThread( )
      {
         // 等待10毫秒，检查 mre是否设置为true。如果没有，继续循环
         while(!event.WaitOne(10))
         {
              remote.update()
         }
      }

**Comment by KumoKyaku** [comment]
与设计初衷不符，不满足性能要求。
