### ISSUE TITLE
你好，安装完库出现错误

### ISSUE THREAD

**Issue by stay-cnsj** [KumoKyaku/Megumin.Net#15]
unity版本：2021.3.6 LST
![image](https://user-images.githubusercontent.com/51780373/216652708-31c1f8e8-efc3-49b4-aa60-a2259e509f97.png)
谢谢你的帮助！

**Comment by KumoKyaku** [comment]
98fb86d74c4103950431a4b9d6f8ca6b71d0a996
修复了，重新导入一下新版本

**Comment by stay-cnsj** [comment]
> [98fb86d](https://github.com/KumoKyaku/Megumin.Net/commit/98fb86d74c4103950431a4b9d6f8ca6b71d0a996) 修复了，重新导入一下新版本

好的，谢谢
