### ISSUE TITLE
请问能不能扩展异步回调函数

### ISSUE THREAD

**Issue by stay-cnsj** [KumoKyaku/Megumin.Net#18]
类似于如图Completed += () => {}
![image](https://user-images.githubusercontent.com/51780373/226166708-59c917da-e9fe-428d-a8e6-345b3da5998e.png)

**Comment by KumoKyaku** [comment]
https://github.com/KumoKyaku/Megumin.Net#3-valuetaskobject-onreceiveshort-cmd-int-messageid-object-message  重写这个函数即可

**Comment by stay-cnsj** [comment]
> https://github.com/KumoKyaku/Megumin.Net#3-valuetaskobject-onreceiveshort-cmd-int-messageid-object-message 重写这个函数即可

谢谢你的回答，感谢！

**Comment by stay-cnsj** [comment]
> https://github.com/KumoKyaku/Megumin.Net#3-valuetaskobject-onreceiveshort-cmd-int-messageid-object-message 重写这个函数即可

非常抱歉，使用SendAsync和SendAsyncSafeAwait发送消息，重写该函数不会触发，能否给两个异步方法SendAsync和SendAsyncSafeAwait添加成功执行后的回调函数
类似这样，我们考虑在库内封装更便捷，不知道是否考虑不周，感谢你的帮助！
<img width="395" alt="80ad1e50e73025cacfd12f6142f5cf2" src="https://user-images.githubusercontent.com/51780373/227601327-e5eab0e2-4381-4b10-9ba3-0509d057d165.png">

**Comment by KumoKyaku** [comment]
抱歉，之前是我理解错了。OnReceive是接收端的回调函数。不是SendAysnc的回调函数。
目前框架设计中没有为SendAysnc设计回调函数，因为当前没有遇到这样的需求。设计上是调用SendAysnc之后，用户就不用再关系发送情况，全部由框架处理。

框架是可以实现这个功能的，但是会带来一些衍生问题，比如意料之外的内存泄露。
能说下你的用例吗，为什么需要在这里添加回调函数？
如果是我没有考虑到的迫切需求我会添加到框架里，如果是你的特有需求，我可以告诉你在哪里扩展

**Comment by KumoKyaku** [comment]
另外，我想知道你想在回调函数中访问哪些变量，设计怎么样的函数签名，这样设计回调函数的时候可以有选择的传递，防止一些需要控制生命周期的变量传递到外面。

**Comment by stay-cnsj** [comment]
抱歉，之前表述的不够准确

![image](https://user-images.githubusercontent.com/51780373/227713423-1125784f-f933-4878-a2d1-1fc0542178f2.png)
如图，同步方法不会因为异步阻塞，我们希望异步函数不影响主程执行。在程序库内部利用已经开了的异步线程实现，这样我们不用再开一个线程处理回调 从而节省线程资源。

例如在函数初始化执行构造函数时，我们希望用SendAysnc先从服务器获取数据，若没有获得到数据，仍然可以执行后续与之不相关的代码，与之相关的放在回调函数中执行。

我们设想的函数签名是这样的：
public Result SendAndWaitAsync<T>(object msg, Action<T> callback, Action<Exception> onException);

感谢你的帮助！

**Comment by KumoKyaku** [comment]
我完全糊涂了😅。
public Result SendAndWaitAsync(object msg, Action callback, Action onException); 
为什么这个函数是同步的，我没有理解。
能说明这个函数中callback想要在框架的哪一个位置被调用吗，是socket发送完字节数据之后，还是服务器回消息之后。

**Comment by stay-cnsj** [comment]
<img width="620" alt="1679759594729" src="https://user-images.githubusercontent.com/51780373/227727992-d1589f85-bd5c-4889-b892-c8144a47c3e1.png">

SendAndWaitAsync是异步函数（类似于上图的TestAsync函数），我们希望在同步函数（类似上图的DoSync函数）里调用它，并且在SendAndWaitAsync没收到服务器回的消息时不阻塞同步函数里面的其他代码。如上图，同步函数内不会被异步函数阻塞，会执行WriteLine打印，之后等异步函数执行完毕，将结果传入回调函数执行

public Result SendAndWaitAsync(object msg, Action callback, Action onException);
这个是我们设想你能提供的异步函数签名，在你的原有基础上添加了服务器回消息后的回调callback，客户端socket发送完字节数据之后不考虑

**Comment by KumoKyaku** [comment]
我还是没有理解你的意思，不过这样扩展函数能满足你们的需求吗？
你可以将这段代码复制到你们项目的任何位置。然后可以通过ISendAsyncable 调用这个函数，就像这个函数在框架中存在一样。
```
public static class Extension
{
    public static async void MySendAndWaitAsync<Result>(this ISendAsyncable send,
                                                      object msg,
                                                      Action callback,
                                                      Action onException)
    {
        var (result, exception) = await send.SendAsync<Result>(msg);
        if (exception != null)
        {
            onException?.Invoke();
        }
        else
        {
            callback?.Invoke();
        }
    }

    public static async ValueTask<Result> MySendAndWaitAsync2<Result>(this ISendAsyncable send,
                                                                    object msg,
                                                                    Action callback,
                                                                    Action onException)
    {
        var (result, exception) = await send.SendAsync<Result>(msg);
        if (exception != null)
        {
            onException?.Invoke();
            return default;
        }
        else
        {
            callback?.Invoke();
            return result;
        }
    }

    public static void DoSync(ISendAsyncable send)
    {
        var msg = new object();
        send.MySendAndWaitAsync<object>(msg, callback: () => { }, onException: () => { });
        Console.WriteLine("");
    }
}
```
异步函数如果要有返回值只能是Task<T>,ValueTask<T>,void。

**Comment by KumoKyaku** [comment]
https://github.com/KumoKyaku/Megumin.Net/blob/master/NetRemoteStandard/Extension.cs#L14
可以参考下，常用的接口API都是通过扩展函数实现的，接口原始API签名很复杂调用不方便。通过扩展函数增加自己喜欢的函数签名。

**Comment by stay-cnsj** [comment]
谢谢你的帮助，我们对框架有了更多的了解，目前满足了需求
